//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryCost
    {
        public Nullable<System.DateTime> Дата_изменения { get; set; }
        public int Артикул_книги { get; set; }
        public Nullable<decimal> Стара_цена { get; set; }
        public Nullable<decimal> Новаая_цена { get; set; }
    
        public virtual Книги Книги { get; set; }
    }
}
