//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Детали_заказа
    {
        public int Номер_заказа { get; set; }
        public int Артикул_книги { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Книги Книги { get; set; }
    }
}
