//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Книги
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Книги()
        {
            this.Детали_заказа = new HashSet<Детали_заказа>();
        }
    
        public int Артикул_книги { get; set; }
        public string Название { get; set; }
        public Nullable<int> Номер_жанра { get; set; }
        public string Единица_измерения { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<System.DateTime> Год_издания { get; set; }
        public byte[] Изображение { get; set; }
        public Nullable<int> Номер_издателя { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Детали_заказа> Детали_заказа { get; set; }
        public virtual Жанры Жанры { get; set; }
        public virtual Издатели Издатели { get; set; }
        public virtual HistoryCost HistoryCost { get; set; }
    }
}
